#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\KinesiologoController::inicioApp

loginKinesiologo:
    path: /login
    controller: App\Controller\KinesiologoController::login

logout:
    path: /logout

home:
    path: /home
    controller: App\Controller\KinesiologoController::home

homePaciente:
    path: /home_paciente
    controller: App\Controller\PacienteController::home

agregarKinesiologo:
    path: /agregar_kinesiologo
    controller: App\Controller\KinesiologoController::addKinesiologo

listarKinesiologo:
    path: /listar_kinesiologos
    controller: App\Controller\KinesiologoController::listKinesiologos

agregarPaciente:
    path: /agregar_paciente
    controller: App\Controller\PacienteController::addPaciente

agregarAntecedentesClinicos:
  path: /antecedentes_clinicos/{pacienteId}
  controller: App\Controller\PacienteController::addAntecedentesClinicos

listarPaciente:
    path: /listar_pacientes
    controller: App\Controller\PacienteController::listPacientes

chat:
    path: /chats
    controller: App\Controller\KinesiologoController::chat

agregarEjercicio:
    path: /agregar_ejercicio
    controller: App\Controller\EjercicioController::addEjercicio

datosPaciente:
    path: /datos_paciente/{paciente}
    controller: App\Controller\PacienteController::dataPaciente
    defaults:
        paciente: 0

eliminarPaciente:
    path: /eliminar_paciente/{paciente}
    controller: App\Controller\PacienteController::deletePaciente
    defaults:
        paciente: 0
        
editarPaciente:
    path: /editar_paciente/{paciente}
    controller: App\Controller\PacienteController::editPaciente
        
planificacionEjercicios:
    path: /planificacion_ejercicio/{paciente}
    controller: App\Controller\PacienteController::planificacionPaciente
    defaults:
        paciente: 0

mantenedorEjercicios:
    path: /gestion_ejercicios
    controller: App\Controller\EjercicioController::listarEjercicios

editarEjercicio:
    path: /editar_ejercicio/{id}
    controller: App\Controller\EjercicioController:edit

eliminarEjercicio:
    path: /tarea/delete/{id}
    controller: App\Controller\EjercicioController:delete

registrarEjercicio:
    path: /paciente/registrar
    controller: App\Controller\PacienteController::registrarEjercicio

verEjercicio:
  path: /paciente/ejercicio/{ejercicio}
  controller: App\Controller\PacienteController::verEjercicio
  defaults:
    ejercicio: 0

historialKinesiologo:
  path: /paciente/historial_ejercicio/{paciente}
  controller: App\Controller\PacienteController::historialKinesiologo
  defaults:
    paciente: 0

dejarComentario:
  path: /paciente/comentario/{kinesiologo}
  controller: App\Controller\PacienteController::dejarComentario
  defaults:
    kinesiologo: 0

historialPaciente:
  path: /historial_paciente
  controller: App\Controller\KinesiologoController::historialPaciente

calificacion:
  path: /calificacion/{paciente}
  controller: App\Controller\KinesiologoController::calificacion
  defaults:
    paciente: 0

comenzarRutina:
  path: /paciente/rutina/{rutina}/{ejercicio}
  controller: App\Controller\PacienteController::comenzarRutina
  defaults:
    rutina: 0
    ejercicio: 0

evaluarEjercicio:
    path: /paciente/evaluarEjercicio/{ejercicio}/{paciente}/{rutina}
    controller: App\Controller\PacienteController::evaluarEjercicio
    defaults:
        ejercicio: 0
        paciente: 0
        rutina: 0