#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
    path: /
    controller: App\Controller\KinesiologoController::login

logout:
    path: /logout

home:
    path: /home
    controller: App\Controller\KinesiologoController::home

agregarKinesiologo:
    path: /agregar_kinesiologo
    controller: App\Controller\KinesiologoController::addKinesiologo

listarKinesiologo:
    path: /listar_kinesiologos
    controller: App\Controller\KinesiologoController::listKinesiologos

agregarPaciente:
    path: /agregar_paciente
    controller: App\Controller\PacienteController::addPaciente

listarPaciente:
    path: /listar_pacientes
    controller: App\Controller\PacienteController::listPacientes

chat:
    path: /chats
    controller: App\Controller\KinesiologoController::chat

agregarEjercicio:
    path: /agregar_ejercicio
    controller: App\Controller\EjercicioController::addEjercicio

datosPaciente:
    path: /datos_paciente/{paciente}
    controller: App\Controller\PacienteController::dataPaciente
    defaults:
        paciente: 0